### ISSUE TITLE
Uncaught Exception - Cannot call map of undefined

### ISSUE THREAD

**Issue by DuncanFenning** [holidayextras/jsonapi-client#13]
This seems to be mapping errors in the response of _action function

`Uncaught exception! TypeError: Cannot call method 'map' of undefined
    at [...]/node_modules/jsonapi-client/lib/Transport.js:48:40`

**Comment by theninj4** [comment]
Hi @DuncanFenning - can you provide any more information? It'd be great to understand the payload that caused the crash. Was the payload a valid `json:api` document?
