### ISSUE TITLE
Remove resource id in POST request instead of send the null value

### ISSUE THREAD

**Issue by danielebriggi** [holidayextras/jsonapi-client#36]
When is created a resource for POST purpose, the _id_ attribute is initialised to null.

In the jsonapi.org specifications is not specified that the id _must not_ be present in case of server-generated id but should not be better to avoid to send id set to _null_ by default in POST request and do not send it all?

In my case the PHP lib that I use https://github.com/cloudcreativity/json-api doesn't expect by default the _id_ attribute when the id is not generated client-side. If present (even if null) but not expected the validation fails. I think that it's the right choice, it should not be set.

**Comment by theninj4** [comment]
Fixed in v0.7.0
