### ISSUE TITLE
Add options to fetch function

### ISSUE THREAD

**Issue by danielebriggi** [holidayextras/jsonapi-client#39]
The `fetch` function on a resource uses the `related` link to retrieve resources related to the primary data. For the JSON:Api specifications the `related` link returns the `resource object\s`.
It seems that the `options` in the `related` link still respects the specifications.
Why is not considered this case in the `fetch` request? 
Even `relationships` links may have `inclusion` parameter in query string.

This is my proposal, it's pretty simple actually: https://github.com/danielebriggi/jsonapi-client/commit/9f8490ea2d53d674d804c286b389746706ac181a

**Comment by theninj4** [comment]
I think that's a nice addition :+1: If you want to put in a pull request to this project, I'll happily merge it in :)

**Comment by danielebriggi** [comment]
sure!
