### ISSUE TITLE
Uncaught ReferenceError: JsonapiClient is not defined

### ISSUE THREAD

**Issue by fabiobon** [holidayextras/jsonapi-client#8]
I've tried to use JsonapiClient client in browser but i've got some errors.
following documentation var JsonapiClient = require("jsonapi-client"); creates error:
Uncaught ReferenceError: require is not defined.
Have you got any solution?
Thanks

**Comment by fabiobon** [comment]
I've tried to compile index.js (service with all methods) throw webpack, and now callings have some errors. for example:

> client.find("articles", { 
>         include: ["photos","author"],
>     }, function(err, resources) {
>         var treeView = resources.map(function(resource) {
>         console.log(resource.toJSON());
>     });
> });

retrive following errors:
OPTIONS http://localhost:16006/rest/articles 
XMLHttpRequest cannot load http://localhost:16006/rest/articles. Invalid HTTP status code 404

Note:
standalone calling: 

> http://localhost:16006/rest/articles
> works correctly

Have you got any suggestion?
Thanks

**Comment by theninj4** [comment]
Sorry for the delay, I've only just seen this issue :disappointed: There is a browserified version of this module in the `dist` folder that should be loadable via a `<script ...` tag in a browser. It might be missing something trivial, I'll put together an in-browser test suite to demonstrate it working. :+1:

**Comment by fabiobon** [comment]
Suggestion:
I've tried a standalone superagent calling

> "use strict"
> var request = require('superagent');
> request
> .get('http://localhost:16006/rest/articles') 
> .accept('application/vnd.api+json')
> .type('application/vnd.api+json')
> .end(function(err, res){
>     if(err) console.log(err);
>     console.log(res.body);
> });

in node res.body and res.text are filled
in browser res.body is null, instead res.text is filled

then i've found this
https://github.com/visionmedia/superagent/issues/636

**Comment by fabiobon** [comment]
Top! Late night good wine...

**Comment by theninj4** [comment]
You should be good to go as soon as #11 is merged, there's a new usage example in the README and #11 proves we're supporting a range of browsers with no visible CORS issues.
